# Generated by Django 2.1 on 2023-04-20 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.IntegerField()),
                ('post', models.CharField(max_length=2000)),
                ('author', models.CharField(max_length=255)),
                ('comment', models.CharField(max_length=2000)),
                ('likes_counter', models.IntegerField()),
            ],
        ),
    ]
