# Generated by Django 2.1 on 2023-04-20 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='post',
            field=models.TextField(max_length=2000),
        ),
    ]
