# Generated by Django 2.1 on 2023-04-22 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20230420_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='comment',
            field=models.TextField(max_length=2000),
        ),
    ]
