# Generated by Django 2.1 on 2023-04-22 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20230422_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='dislike_counter',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
