# Generated by Django 2.1 on 2023-04-22 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20230422_1713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs',
            name='date',
        ),
    ]
