# Generated by Django 2.1 on 2023-04-14 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_name', models.CharField(max_length=255)),
                ('prod_price', models.FloatField()),
                ('prod_stock', models.IntegerField()),
                ('prod_img_url', models.CharField(max_length=255)),
            ],
        ),
    ]
