# Generated by Django 2.1 on 2023-04-22 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='prod_producer',
            field=models.CharField(default='Pyshop Original', max_length=255, null=True),
        ),
    ]
