# Generated by Django 2.1 on 2023-04-23 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_products_prod_producer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='prod_price',
            field=models.DecimalField(decimal_places=2, max_digits=2000),
        ),
    ]
