# Generated by Django 2.1 on 2023-05-21 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20230517_1945'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='prod_name',
            new_name='prodname',
        ),
    ]
