# Generated by Django 2.1 on 2023-05-22 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20230521_1457'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='prodname',
            new_name='prod_name',
        ),
    ]
