# Generated by Django 2.1 on 2023-05-22 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20230523_0039'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='prod_name',
            new_name='prodname',
        ),
    ]
